#!/bin/bash
#HOST=dbhems.4st.co.kr
HOST=118.67.128.134
USER=root
PASSWORD='R3U?@32*7\$J28b'
SFTP_DIR="/data2/dbbackup/hems_db"
DB_BACKUP_DIR="/data/dbbackup/hems_db"
LOG_FILE="/data/dbbackup/hems_db/dbbackup.log"
DATE=`date +%Y%m%d`
DATE_1=`date +%Y%m`"01"
DATE_15=`date +%Y%m`"15"
DIRDATE_YEAR=`date +%Y`"_hems_db"
StartTime=$(date +%s)
StartDate=`date +%Y-%m-%d" "%H:%M:%S`

echo "" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "#############################################################################################" >> $LOG_FILE
echo "########################         START DB BACKUP SFTP v1.0.0    #############################" >> $LOG_FILE
echo "########################         DB   : HEMS_DB                 #############################" >> $LOG_FILE
echo "########################         DATE : $StartDate     #############################" >> $LOG_FILE
echo "#############################################################################################" >> $LOG_FILE
echo "" >> $LOG_FILE

echo "#############################" >> $LOG_FILE
echo "# DBbackup(SFTP)" >> $LOG_FILE
echo "#############################" >> $LOG_FILE		

echo "[DB Sftp] StartTime: $StartDate" >> $LOG_FILE

echo "mkdir -p $DB_BACKUP_DIR/$DIRDATE_YEAR/" >> $LOG_FILE
mkdir -p $DB_BACKUP_DIR/$DIRDATE_YEAR/

echo "if [ $DATE -ge $DATE_15 ]; then" >> $LOG_FILE
echo "FILE_DATE=$DATE_15" >> $LOG_FILE
echo "elif [ $DATE -lt $DATE_15 ]; then" >> $LOG_FILE
echo "FILE_DATE=$DATE_1" >> $LOG_FILE
echo "fi" >> $LOG_FILE

if [ $DATE -ge $DATE_15 ]; then
FILE_DATE=$DATE_15
elif [ $DATE -lt $DATE_15 ]; then
FILE_DATE=$DATE_1
fi

echo "FILE_DATE : $FILE_DATE"

echo "expect -c \"spawn sftp -oPort=22022 $USER@$HOST" >> $LOG_FILE
echo "expect \"password:\" send \"cd $SFTP_DIR\n\"" >> $LOG_FILE
echo "expect \"sftp>\" send \"lcd $DB_BACKUP_DIR/$DIRDATE_YEAR/\n\"" >> $LOG_FILE
echo "expect \"sftp>\" send \"get hems_db_raw_$FILE_DATE.tar.gz\n\"" >> $LOG_FILE
echo "expect \"sftp>\" send \"quit\n\"" >> $LOG_FILE
echo "interact \"" >> $LOG_FILE

expect -c "spawn sftp -oPort=22022 $USER@$HOST
expect \"password:\"
send \"$PASSWORD\n\"
expect \"sftp>\"
send \"cd $SFTP_DIR\n\"
expect \"sftp>\"
send \"lcd $DB_BACKUP_DIR/$DIRDATE_YEAR/\n\"
expect \"sftp>\"
send \"get hems_db_raw_$FILE_DATE.tar.gz\n\"
expect \"sftp>\"
send \"quit\n\"
interact "

#FILE_DATE='20230327'

EndTime=$(date +%s)
EndDate=`date +%Y-%m-%d" "%H:%M:%S`
echo "[DB Sftp] EndTime: $EndDate" >> $LOG_FILE
echo "[DB Sftp] It takes $(( $EndTime - $StartTime )) seconds" >> $LOG_FILE

echo "" >> $LOG_FILE
echo "#############################" >> $LOG_FILE
echo "# check log file size" >> $LOG_FILE
echo "#############################" >> $LOG_FILE

FILESIZE=$(wc -c "$LOG_FILE" | awk '{print $1}')
echo "file size: $FILESIZE" >> $LOG_FILE
if [ $FILESIZE -gt 2000000 ];then
  echo "log backup and init ...." >> $LOG_FILE
  /bin/cp -p $LOG_FILE $LOG_FILE.bak
  cat /dev/null > $LOG_FILE
  echo "file size ${FILESIZE} is more than 2000000 and init" >> $LOG_FILE
else 
  echo "file size is not over" >> $LOG_FILE
fi

EndDate=`date +%Y-%m-%d" "%H:%M:%S`
echo "" >> $LOG_FILE
echo "#############################################################################################" >> $LOG_FILE
echo "########################         END DB BACKUP SFTP v1.0.0    ###############################" >> $LOG_FILE
echo "########################         DB   : HEMS_DB               ###############################" >> $LOG_FILE
echo "########################         DATE : $EndDate     #############################" >> $LOG_FILE
echo "#############################################################################################" >> $LOG_FILE
echo "" >> $LOG_FILE
