jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  #프로필 설정
  profiles:
    active: dev

  #view 설정
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  #devtools 설정
  devtools:
    livereload:
      enabled: true

  #database 설정
  datasource:
    #Hikari(springboot 기본 설정)
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ENC(usGJYpNQ8m33rU6obv4aWZqopmbpQjQTLopzZXBKXbODZHxQdUhJEukuSi9XHKc4mgE9QVvgS6dqbLOnrQfOxtL6lgBkAe0hRf6L/lwYuFsXlc5iG3baAoCZJ0V4ljLng3HqCHxGjkgOUcZvqrk7ITfsuXPgo98BblNsqJdq1Ix3tpsNsBZR5kxbq4oMZZUgcT05A3Hmau1qgbDVpOgT+QoFQeadryRFeYyQim06y5U=)
      username: ENC(2uWEuyv9oD27KA2PyVfFedMMhVIcNUPZI845AGXzD/mU6Fy2TVKgkB5FlFV/8FiO)
      password: ENC(In3q14h5m+meWEUsz5ei9N0uYME0rwY1AbT/mXRKX+TzZiUfxgURPImIXmqFgCTn)
      connection-test-query: SELECT 1
      pool-name: SpringBootMyBatisHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000

#mybatis 설정
mybatis:
  type-aliases-package: com.kevin.server_monitor.model
  mapper-locations: /mybatis/mapper/*.xml

#log 설정
logging:
  config: classpath:logback-spring.xml

#톰캣 설정
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 30m
        http-only: true
        secure: false
  tomcat:
    keep-alive-timeout: 30s
    max-keep-alive-requests: 100
    accesslog:
      directory: logs/tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 30
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: access_log
      rotate: true
      suffix: .log
    basedir: .
  port: 443

  #SSL 설정
  ssl:
    enabled: true
    key-store: ENC(iGXDG2IJTlCc7C+F0w1HGlpcnG0iTyQDRx/Ar3OpWQgNtdGRNmbhKanUMZK+cH9uJ7ufp/9syuSpsPOfQFUlAqvFOO3I4+sxtvNVg8uT1gM=)
    key-store-type: ENC(XyJsJjB6F5S/PdfY5ITZ7eVE4wv7RM9YIfVX2Qn4d3wTjFrWbkHgDPghsv2tiZFr)
    key-store-password: ENC(9kC0wx3oaIJwEGX2Hpyayr4weBuPl0j1hnSdiURpxmk72DzBXAlRF+HrB5rYxnqF)

  compression:
    enabled: true